const language = navigator.language;

export function getLocalString(en_us_String) {
  console.log(language);
}

// You - Asa, the keys are written in English, why are you defining an english version of the dictionary
// Me - Easy copy paste for new dictionary
const englishDictionary = {
  "Hours Worked": "Hours Worked",
  Login: "Login",
  Email: "Email",
  Password: "Password",
  "Sign In": "Sign In",
  "Failed to sign in: ": "Failed to sign in: ",
  "Forgot your password?": "Forgot your password?",
  "Log Out": "Log Out",
  "Add Employee": "Add Employee",
  "There has been an error.": "There has been an error.",
  "Error code": "Error code",
  "Please refresh.": "Please refresh.",
  "Your administrator is responsible for sending you a code. Contact your employer to request a code.":
    "Your administrator is responsible for sending you a code. Contact your employer to request a code.",
  "If you are an administrator or don't have an employer that sent you to this website to make an account, email me at asadillahunty@gmail.com":
    "If you are an administrator or don't have an employer that sent you to this website to make an account, email me at asadillahunty@gmail.com",
  Close: "Close",
  "Welcome to Mayfly": "Welcome to Mayfly",
  "Your new timekeeping app": "Your new timekeeping app",
  "Input your code": "Input your code",
  "Don't have a code?": "Don't have a code?",
  Submit: "Submit",
  Sun: "Sun",
  Mon: "Mon",
  Tue: "Tue",
  Wed: "Wed",
  Thu: "Thu",
  Fri: "Fri",
  Sat: "Sat",
  "Error signing out:": "Error signing out:",
  "Failed to update last change.": "Failed to update last change.",
  "Major Error Occurred": "Major Error Occurred",
  "Failed to remove emp company data": "Failed to remove emp company data",
  "Failed to create user": "Failed to create user",
  Confirm: "Confirm",
  Cancel: "Cancel",
  "Company Name": "Company Name",
  "Unregistered Employees": "Unregistered Employees",
  Code: "Code",
  "Failed to delete": "Failed to delete",
  "Are you sure you want to remove": "Are you sure you want to remove",
  from: "from",
  "This action cannot be undone.": "This action cannot be undone.",
  "Edit Hours": "Edit Hours",
  "Add Additional Hours": "Add Additional Hours",
  "Edit Employee Information": "Edit Employee Information",
  "Remove Employee": "Remove Employee",
  "Make Admin": "Make Admin",
  Done: "Done",
  "Hourly Wage not valid": "Hourly Wage not valid",
  "Edit Employee Info": "Edit Employee Info",
  "Create New Employee": "Create New Employee",
  "First Name": "First Name",
  "Last Name": "Last Name",
  "Rate Per Hour": "Rate Per Hour",
  "Month View": "Month View",
  "Week View": "Week View",
  "Weekly total": "Weekly total",
  "Add Hours": "Add Hours",
  Notes: "Notes",
  Save: "Save",
};
