name: Deploy GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] # changed to a fake branch while this isn't working
  pull_request:
    branches: [ main ] # changed to a fake branch while this isn't working

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      # installs dependencies
      - name: Install
        run: npm install
        
      # Builds application
      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy to gh-pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv build/* .
          rm -rf node_modules
          rm -rf build
          git add .
          git commit -m "Deploy to gh-pages"
          git push -f origin gh-pages